"""Fix rooms

Revision ID: 5d7f2a05c4eb
Revises: 34c101ad3a71
Create Date: 2025-12-07 15:37:57.202825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7f2a05c4eb'
down_revision = '34c101ad3a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_types', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_room_types_name", ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
